/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Entity.Tamagochi;

import Connection.Update;
import Images.JPanelImage;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class VentanaTamagochi extends javax.swing.JFrame {
    
    private Tamagochi tamagochi;

    public Tamagochi getTamagochi() {
        return this.tamagochi;
    }

    /**
     * Creates new form VentanaTamagochi
     * @param tamagochi
     */
    public void setTamagochi(Tamagochi tamagochi) {
        this.tamagochi = tamagochi;
    }
    
    public void setearStats(){
        this.jBarVida.setValue(this.tamagochi.getVida());
        this.jBarEnergia.setValue(this.tamagochi.getEnergia());
        this.jBarFelicidad.setValue(this.tamagochi.getFelicidad());
    }
    
    public void setearImagen(String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
           image.getImage().getScaledInstance(jLblImagen.getWidth(), jLblImagen.getHeight(), Image.SCALE_DEFAULT)
        );
        jLblImagen.setIcon(icon);
        this.repaint();
    }
    
    public void setearFondo(){
        JPanelImage mImagen = new JPanelImage(jPnlFondo, "src/Images/arioParada.jpg");
        jPnlFondo.add(mImagen).repaint();
    }

    public VentanaTamagochi(Tamagochi tamagochi) {
        this.tamagochi = tamagochi;
        initComponents();
        setearStats();
        setearImagen("src/Images/eldum.jpg");
        setearFondo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jBtnAlimentar = new javax.swing.JButton();
        jBtnMimar = new javax.swing.JButton();
        jBtnGolpear = new javax.swing.JButton();
        jBtnVolver = new javax.swing.JButton();
        jBarVida = new javax.swing.JProgressBar();
        jBarEnergia = new javax.swing.JProgressBar();
        jBarFelicidad = new javax.swing.JProgressBar();
        jPnlFondo = new javax.swing.JPanel();
        jLblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnl0.setBackground(new java.awt.Color(255, 255, 255));

        jBtnAlimentar.setText("Alimentar");
        jBtnAlimentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlimentarActionPerformed(evt);
            }
        });

        jBtnMimar.setText("Mimar");
        jBtnMimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMimarActionPerformed(evt);
            }
        });

        jBtnGolpear.setText("Golpear");
        jBtnGolpear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGolpearActionPerformed(evt);
            }
        });

        jBtnVolver.setBackground(new java.awt.Color(255, 0, 0));
        jBtnVolver.setText("Volver a Incio");
        jBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolverActionPerformed(evt);
            }
        });

        jBarVida.setBackground(java.awt.Color.red);
        jBarVida.setStringPainted(true);

        jBarEnergia.setBackground(new java.awt.Color(51, 255, 51));
        jBarEnergia.setStringPainted(true);

        jBarFelicidad.setBackground(new java.awt.Color(255, 255, 0));
        jBarFelicidad.setStringPainted(true);

        jPnlFondo.setDoubleBuffered(false);

        javax.swing.GroupLayout jPnlFondoLayout = new javax.swing.GroupLayout(jPnlFondo);
        jPnlFondo.setLayout(jPnlFondoLayout);
        jPnlFondoLayout.setHorizontalGroup(
            jPnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFondoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPnlFondoLayout.setVerticalGroup(
            jPnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlFondoLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnl0Layout.createSequentialGroup()
                        .addComponent(jBarEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBarFelicidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBarVida, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPnl0Layout.createSequentialGroup()
                            .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBtnVolver)
                                .addComponent(jBtnAlimentar)
                                .addComponent(jBtnGolpear)
                                .addComponent(jBtnMimar))
                            .addGap(38, 38, 38)
                            .addComponent(jPnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBarVida, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBarFelicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBarEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addComponent(jBtnAlimentar)
                        .addGap(26, 26, 26)
                        .addComponent(jBtnMimar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnGolpear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnVolver)
                        .addGap(30, 30, 30))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addComponent(jPnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolverActionPerformed
        // TODO add your handling code here:
        Update update = new Update();
        update.updateTamagochi(this.tamagochi, this.tamagochi.getId());
        VentanaInicio newFrame = new VentanaInicio();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnVolverActionPerformed

    private void jBtnAlimentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlimentarActionPerformed
        // TODO add your handling code here:
        int vida = (this.tamagochi.getVida() < 100) ? (this.tamagochi.getVida() + 1) : (this.tamagochi.getVida());
        int energia = (this.tamagochi.getEnergia() < 100) ? (this.tamagochi.getEnergia() + 1): this.tamagochi.getEnergia();
        this.tamagochi.setEnergia(energia);
        this.tamagochi.setVida(vida);
        setearStats();
    }//GEN-LAST:event_jBtnAlimentarActionPerformed

    private void jBtnMimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMimarActionPerformed
        // TODO add your handling code here:
        int felicidad = (this.tamagochi.getFelicidad()< 100) ? (this.tamagochi.getFelicidad()+ 1): this.tamagochi.getFelicidad();
        this.tamagochi.setFelicidad(felicidad);
        setearStats();
    }//GEN-LAST:event_jBtnMimarActionPerformed

    private void jBtnGolpearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGolpearActionPerformed
        // TODO add your handling code here:
        int vida = (this.tamagochi.getVida() > 0) ? (this.tamagochi.getVida() - 1) : 0;
        int energia = (this.tamagochi.getEnergia() > 0) ? (this.tamagochi.getEnergia() - 1) : 0;
        int felicidad = (this.tamagochi.getFelicidad() > 0) ? (this.tamagochi.getFelicidad() - 1) : 0;
        this.tamagochi.setVida(vida);
        this.tamagochi.setEnergia(energia);
        this.tamagochi.setFelicidad(felicidad);
        setearStats();
    }//GEN-LAST:event_jBtnGolpearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTamagochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTamagochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTamagochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTamagochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTamagochi(new Tamagochi()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jBarEnergia;
    private javax.swing.JProgressBar jBarFelicidad;
    private javax.swing.JProgressBar jBarVida;
    private javax.swing.JButton jBtnAlimentar;
    private javax.swing.JButton jBtnGolpear;
    private javax.swing.JButton jBtnMimar;
    private javax.swing.JButton jBtnVolver;
    private javax.swing.JLabel jLblImagen;
    private javax.swing.JPanel jPnl0;
    private javax.swing.JPanel jPnlFondo;
    // End of variables declaration//GEN-END:variables
}
